#!/usr/bin/env bash
set -euo pipefail

# Auto-generated by generate-installers.ts — do not edit manually
# Installs the "antigravity-chat-read" skill to ~/.claude/skills/antigravity-chat-read/

SKILL_DIR="$HOME/.claude/skills/antigravity-chat-read"
REPO_BASE="https://raw.githubusercontent.com/mameikagou/skill-forge/main/skills/antigravity-chat-read"

echo "Installing antigravity-chat-read..."

# Create directory structure
mkdir -p "$SKILL_DIR"
mkdir -p "$SKILL_DIR/scripts"

# Download files
curl -fsSL "$REPO_BASE/SKILL.md" -o "$SKILL_DIR/SKILL.md"
curl -fsSL "$REPO_BASE/scripts/cli.test.ts" -o "$SKILL_DIR/scripts/cli.test.ts"
curl -fsSL "$REPO_BASE/scripts/cli.ts" -o "$SKILL_DIR/scripts/cli.ts"

# Verify
if [ ! -f "$SKILL_DIR/SKILL.md" ]; then
  echo "ERROR: Installation failed - SKILL.md not found"
  rm -rf "$SKILL_DIR"
  exit 1
fi

echo ""
echo "antigravity-chat-read installed successfully!"
echo "  Location: $SKILL_DIR"
echo "  To uninstall: rm -rf $SKILL_DIR"
