#!/usr/bin/env bash
set -euo pipefail

# Auto-generated by skill-auto-installer
# Installs the "anti-ai-writing" skill to ~/.claude/skills/anti-ai-writing/

SKILL_DIR="$HOME/.claude/skills/anti-ai-writing"
REPO_BASE="https://raw.githubusercontent.com/mameikagou/skill-forge/main/skills/anti-ai-writing"

echo "Installing anti-ai-writing..."

# Create directory structure
mkdir -p "$SKILL_DIR"

# Download files
curl -fsSL "$REPO_BASE/SKILL.md" -o "$SKILL_DIR/SKILL.md"

# Verify
if [ ! -f "$SKILL_DIR/SKILL.md" ]; then
  echo "ERROR: Installation failed - SKILL.md not found"
  rm -rf "$SKILL_DIR"
  exit 1
fi

# Verify YAML frontmatter exists
if ! head -1 "$SKILL_DIR/SKILL.md" | grep -q "^---"; then
  echo "ERROR: Installation failed - SKILL.md has invalid frontmatter"
  rm -rf "$SKILL_DIR"
  exit 1
fi

echo ""
echo "anti-ai-writing installed successfully!"
echo "  Location: $SKILL_DIR"
echo "  Trigger: 当用户要求降 AI 率、去 AI 味、降低查重率、改写论文时触发"
echo "  To uninstall: rm -rf $SKILL_DIR"
