#!/usr/bin/env bash
set -euo pipefail

# Auto-generated by generate-installers.ts — do not edit manually
# Installs the "write-skill" skill to ~/.claude/skills/write-skill/

SKILL_DIR="$HOME/.claude/skills/write-skill"
REPO_BASE="https://raw.githubusercontent.com/mameikagou/cheap-hands/main/skills/write-skill"

echo "Installing write-skill..."

# Create directory structure
mkdir -p "$SKILL_DIR"
mkdir -p "$SKILL_DIR/references"
mkdir -p "$SKILL_DIR/scripts"

# Download files
curl -fsSL "$REPO_BASE/references/agent-skills-spec.md" -o "$SKILL_DIR/references/agent-skills-spec.md"
curl -fsSL "$REPO_BASE/references/claude-code-extensions.md" -o "$SKILL_DIR/references/claude-code-extensions.md"
curl -fsSL "$REPO_BASE/SKILL.md" -o "$SKILL_DIR/SKILL.md"
curl -fsSL "$REPO_BASE/scripts/install.ts" -o "$SKILL_DIR/scripts/install.ts"

# Verify
if [ ! -f "$SKILL_DIR/SKILL.md" ]; then
  echo "ERROR: Installation failed - SKILL.md not found"
  rm -rf "$SKILL_DIR"
  exit 1
fi

echo ""
echo "write-skill installed successfully!"
echo "  Location: $SKILL_DIR"
echo "  To uninstall: rm -rf $SKILL_DIR"
