#!/usr/bin/env bash
set -euo pipefail

# Auto-generated by generate-installers.ts — do not edit manually
# Installs the "skill-auto-installer" skill to ~/.claude/skills/skill-auto-installer/

SKILL_DIR="$HOME/.claude/skills/skill-auto-installer"
REPO_BASE="https://raw.githubusercontent.com/mameikagou/cheap-hands/main/skills/skill-auto-installer"

echo "Installing skill-auto-installer..."

# Create directory structure
mkdir -p "$SKILL_DIR"
mkdir -p "$SKILL_DIR/scripts"

# Download files
curl -fsSL "$REPO_BASE/scripts/install.ts" -o "$SKILL_DIR/scripts/install.ts"
curl -fsSL "$REPO_BASE/SKILL.md" -o "$SKILL_DIR/SKILL.md"

# Verify
if [ ! -f "$SKILL_DIR/SKILL.md" ]; then
  echo "ERROR: Installation failed - SKILL.md not found"
  rm -rf "$SKILL_DIR"
  exit 1
fi

echo ""
echo "skill-auto-installer installed successfully!"
echo "  Location: $SKILL_DIR"
echo "  To uninstall: rm -rf $SKILL_DIR"
